--
-- PostgreSQL database dump
--

\restrict BbxC4zOKhdc2r4FnNn5GAUyWvgWgLd44FFmr9PE3Qn8nkzheKHvRplbgATp3wY7

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-05-11 02:51:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 16389)
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- TOC entry 6125 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 232 (class 1259 OID 17512)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17511)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 17522)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17521)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 17502)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17501)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 17531)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 17550)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 17549)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 17530)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 17559)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 17558)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 17620)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 17619)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17490)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17489)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17478)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17477)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 17660)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 269 (class 1259 OID 18795)
-- Name: restaurants_amenitycategory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_amenitycategory (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    icon character varying(50) NOT NULL,
    description text NOT NULL,
    "order" integer NOT NULL
);


ALTER TABLE public.restaurants_amenitycategory OWNER TO postgres;

--
-- TOC entry 268 (class 1259 OID 18794)
-- Name: restaurants_amenitycategory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_amenitycategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_amenitycategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 17738)
-- Name: restaurants_dish; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_dish (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    description text NOT NULL,
    price numeric(10,0) NOT NULL,
    image character varying(100),
    is_available boolean NOT NULL,
    restaurant_id bigint NOT NULL,
    is_price_representative boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.restaurants_dish OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 17737)
-- Name: restaurants_dish_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_dish ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_dish_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 17829)
-- Name: restaurants_feedback; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_feedback (
    id bigint NOT NULL,
    customer_name character varying(100) NOT NULL,
    customer_email character varying(254) NOT NULL,
    rating integer NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_read boolean NOT NULL,
    restaurant_id bigint NOT NULL
);


ALTER TABLE public.restaurants_feedback OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 17828)
-- Name: restaurants_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 18718)
-- Name: restaurants_passwordresettoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_passwordresettoken (
    id bigint NOT NULL,
    token character varying(100) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_used boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.restaurants_passwordresettoken OWNER TO postgres;

--
-- TOC entry 266 (class 1259 OID 18717)
-- Name: restaurants_passwordresettoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_passwordresettoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_passwordresettoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 18006)
-- Name: restaurants_pickuporder; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_pickuporder (
    id bigint NOT NULL,
    customer_name character varying(100) NOT NULL,
    customer_phone character varying(20) NOT NULL,
    pickup_time timestamp with time zone NOT NULL,
    note text NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    restaurant_id bigint NOT NULL,
    user_id integer
);


ALTER TABLE public.restaurants_pickuporder OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 18005)
-- Name: restaurants_pickuporder_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_pickuporder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_pickuporder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 18022)
-- Name: restaurants_pickuporderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_pickuporderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    dish_id bigint NOT NULL,
    pickup_order_id bigint NOT NULL,
    CONSTRAINT restaurants_pickuporderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.restaurants_pickuporderitem OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 18021)
-- Name: restaurants_pickuporderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_pickuporderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_pickuporderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 17711)
-- Name: restaurants_reservation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_reservation (
    id bigint NOT NULL,
    customer_name character varying(100) NOT NULL,
    booking_time timestamp with time zone NOT NULL,
    number_of_people integer NOT NULL,
    table_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    user_id integer,
    queue_position integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    customer_phone character varying(20) NOT NULL,
    note text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT restaurants_reservation_number_of_people_fb8004f6_check CHECK ((number_of_people >= 0)),
    CONSTRAINT restaurants_reservation_queue_position_check CHECK ((queue_position >= 0))
);


ALTER TABLE public.restaurants_reservation OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 17710)
-- Name: restaurants_reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 18678)
-- Name: restaurants_reservationitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_reservationitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    dish_id bigint NOT NULL,
    reservation_id bigint NOT NULL,
    CONSTRAINT restaurants_reservationitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.restaurants_reservationitem OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 18677)
-- Name: restaurants_reservationitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_reservationitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_reservationitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 17687)
-- Name: restaurants_restaurant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_restaurant (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    address character varying(300) NOT NULL,
    location public.geometry(Point,4326) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    district character varying(10) NOT NULL,
    image character varying(100),
    is_pickup_available boolean NOT NULL,
    description text,
    long_description text
);


ALTER TABLE public.restaurants_restaurant OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 17686)
-- Name: restaurants_restaurant_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_restaurant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_restaurant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 271 (class 1259 OID 18810)
-- Name: restaurants_restaurantamenity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_restaurantamenity (
    id bigint NOT NULL,
    is_available boolean NOT NULL,
    note text NOT NULL,
    category_id bigint NOT NULL,
    restaurant_id bigint NOT NULL
);


ALTER TABLE public.restaurants_restaurantamenity OWNER TO postgres;

--
-- TOC entry 270 (class 1259 OID 18809)
-- Name: restaurants_restaurantamenity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_restaurantamenity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_restaurantamenity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 17845)
-- Name: restaurants_restaurantimage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_restaurantimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    created_at timestamp with time zone CONSTRAINT restaurants_restaurantimage_uploaded_at_not_null NOT NULL,
    restaurant_id bigint NOT NULL
);


ALTER TABLE public.restaurants_restaurantimage OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 17844)
-- Name: restaurants_restaurantimage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_restaurantimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_restaurantimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 17700)
-- Name: restaurants_table; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_table (
    id bigint NOT NULL,
    table_number character varying(10) NOT NULL,
    capacity integer NOT NULL,
    is_available boolean NOT NULL,
    restaurant_id bigint NOT NULL,
    CONSTRAINT restaurants_table_capacity_6205adee_check CHECK ((capacity >= 0))
);


ALTER TABLE public.restaurants_table OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 17699)
-- Name: restaurants_table_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 17809)
-- Name: restaurants_testuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_testuser (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.restaurants_testuser OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 17808)
-- Name: restaurants_testuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_testuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_testuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 18704)
-- Name: restaurants_userprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_userprofile (
    id bigint NOT NULL,
    email_verified boolean NOT NULL,
    email_verification_token character varying(100) NOT NULL,
    email_verification_expires timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.restaurants_userprofile OWNER TO postgres;

--
-- TOC entry 264 (class 1259 OID 18703)
-- Name: restaurants_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 6080 (class 0 OID 17512)
-- Dependencies: 232
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 6082 (class 0 OID 17522)
-- Dependencies: 234
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 6078 (class 0 OID 17502)
-- Dependencies: 230
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add restaurant	7	add_restaurant
26	Can change restaurant	7	change_restaurant
27	Can delete restaurant	7	delete_restaurant
28	Can view restaurant	7	view_restaurant
29	Can add table	9	add_table
30	Can change table	9	change_table
31	Can delete table	9	delete_table
32	Can view table	9	view_table
33	Can add reservation	8	add_reservation
34	Can change reservation	8	change_reservation
35	Can delete reservation	8	delete_reservation
36	Can view reservation	8	view_reservation
37	Can add dish	10	add_dish
38	Can change dish	10	change_dish
39	Can delete dish	10	delete_dish
40	Can view dish	10	view_dish
41	Can add test model	11	add_testmodel
42	Can change test model	11	change_testmodel
43	Can delete test model	11	delete_testmodel
44	Can view test model	11	view_testmodel
45	Can add test model2	12	add_testmodel2
46	Can change test model2	12	change_testmodel2
47	Can delete test model2	12	delete_testmodel2
48	Can view test model2	12	view_testmodel2
49	Can add feedback	13	add_feedback
50	Can change feedback	13	change_feedback
51	Can delete feedback	13	delete_feedback
52	Can view feedback	13	view_feedback
53	Can add test user	14	add_testuser
54	Can change test user	14	change_testuser
55	Can delete test user	14	delete_testuser
56	Can view test user	14	view_testuser
57	Can add Ảnh quán ăn	15	add_restaurantimage
58	Can change Ảnh quán ăn	15	change_restaurantimage
59	Can delete Ảnh quán ăn	15	delete_restaurantimage
60	Can view Ảnh quán ăn	15	view_restaurantimage
61	Can add pickup order	16	add_pickuporder
62	Can change pickup order	16	change_pickuporder
63	Can delete pickup order	16	delete_pickuporder
64	Can view pickup order	16	view_pickuporder
65	Can add pickup order item	17	add_pickuporderitem
66	Can change pickup order item	17	change_pickuporderitem
67	Can delete pickup order item	17	delete_pickuporderitem
68	Can view pickup order item	17	view_pickuporderitem
69	Can add Chi tiết đơn đặt bàn	18	add_reservationitem
70	Can change Chi tiết đơn đặt bàn	18	change_reservationitem
71	Can delete Chi tiết đơn đặt bàn	18	delete_reservationitem
72	Can view Chi tiết đơn đặt bàn	18	view_reservationitem
73	Can add Token reset mật khẩu	19	add_passwordresettoken
74	Can change Token reset mật khẩu	19	change_passwordresettoken
75	Can delete Token reset mật khẩu	19	delete_passwordresettoken
76	Can view Token reset mật khẩu	19	view_passwordresettoken
77	Can add Thông tin người dùng	20	add_userprofile
78	Can change Thông tin người dùng	20	change_userprofile
79	Can delete Thông tin người dùng	20	delete_userprofile
80	Can view Thông tin người dùng	20	view_userprofile
81	Can add Bài viết giới thiệu	21	add_restaurantintroduction
82	Can change Bài viết giới thiệu	21	change_restaurantintroduction
83	Can delete Bài viết giới thiệu	21	delete_restaurantintroduction
84	Can view Bài viết giới thiệu	21	view_restaurantintroduction
85	Can add Danh mục tiện ích	22	add_amenitycategory
86	Can change Danh mục tiện ích	22	change_amenitycategory
87	Can delete Danh mục tiện ích	22	delete_amenitycategory
88	Can view Danh mục tiện ích	22	view_amenitycategory
89	Can add Tiện ích quán ăn	23	add_restaurantamenity
90	Can change Tiện ích quán ăn	23	change_restaurantamenity
91	Can delete Tiện ích quán ăn	23	delete_restaurantamenity
92	Can view Tiện ích quán ăn	23	view_restaurantamenity
\.


--
-- TOC entry 6084 (class 0 OID 17531)
-- Dependencies: 236
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
12	pbkdf2_sha256$1200000$EmAc9cSvjjDBitbWNe7fzb$FdhcKS7X7OJlZOgiQfQrhwjD6NWmiMTITFRSP5qtnlM=	2026-04-21 06:42:56.496966+07	f	test4			toanchaut72222@gmail.com	f	t	2026-04-21 06:41:57.439904+07
2	pbkdf2_sha256$1200000$cka4ovsYlS7lVQBKt6XXkR$1DT2+40ZtdA7PUrak7M3LYdnb0QXQhBzZ9LWw8bF03c=	2026-02-06 07:08:47.642341+07	f	ssssss				f	t	2026-02-06 07:08:47.107181+07
3	pbkdf2_sha256$1200000$pzUU4lhwbnzflghvBjkhoA$BShRLZvVxMWzZOrWWEC4xwNYCkMWg5uo+1DPEz7OsE0=	2026-02-06 07:10:53.159688+07	f	ssssss123				f	t	2026-02-06 07:10:52.719502+07
5	pbkdf2_sha256$1200000$ZQJ1QnOspujRiSlVwRhXZu$zITdNdcR5opqXYFHYF34tADzrWu++Rk5xGdHUrhBdOY=	2026-03-06 14:23:59.233514+07	f	usertoaa				f	t	2026-03-06 14:23:58.685183+07
13	pbkdf2_sha256$1200000$WFrJQFG4bKEhWB6TrWiV6O$uKNezbevhDPlp5MRye+ozdkE7CulyFZ9BXPdyviXOvE=	2026-04-21 09:31:10.139141+07	f	test5			toanchaut72223@gmail.com	f	t	2026-04-21 09:30:06.362191+07
1	pbkdf2_sha256$1200000$bdvoGUEAqEprc2hAanoBJO$vpC9FMTEnpls2FbpNhr10dXwqbKHTrMwOqM08miunIs=	2026-05-09 02:36:02.319219+07	t	admin			toanchaut7@gmail.com	t	t	2026-02-02 10:58:24.80682+07
14	pbkdf2_sha256$1200000$T9vbKrJMI64dOXhmP541r7$GpPReeee/2asu6S0wtTqX/NkNvKMId7YYAj7oTLAZdg=	\N	f	2t			admin21@gmail.com	f	t	2026-05-09 02:32:56.999431+07
6	pbkdf2_sha256$1200000$Vxpr4cKLrMQdxRd5sAhfD7$FwhBbiyIPKdf7vhgE5MHt2uIeLwlgH3aB9c/qMk/pC4=	\N	f	sdadasd			toanchau199@gmail.com	f	t	2026-04-20 14:02:31.905474+07
4	pbkdf2_sha256$1200000$icdGWWwoxFBLFg2E2XzqPD$dJUhzC0GiS1IIia8gMSOj3/pF5SpmeSc4YivmamdVIk=	2026-04-20 14:03:26.943442+07	f	dsadsad				f	t	2026-02-06 07:12:39.907044+07
7	pbkdf2_sha256$1200000$yNANC5PHA8ZdoxpR85vkey$B/3lr0SRJVVb43toIg91m3ARrdaQYqkRJbNYjOLLfAA=	\N	f	dssadas			toanchaut721231@gmail.com	f	t	2026-04-20 17:09:25.76259+07
8	pbkdf2_sha256$1200000$dhIsuLyP1ykdsIAeFEWnv7$VP5bZp5Al8DavpnHbVCs6QKoSwMBjNUAjvbJ9Mu4U9Q=	\N	f	test1			toanchaut7212321321@gmail.com	f	t	2026-04-20 17:13:15.850192+07
9	pbkdf2_sha256$1200000$MJKPUzmFfOgvprylZqQ8k9$t9ybR1vL91l03KZK32JzIzBcyIdbSD5+vRdbY+HlEfc=	2026-04-20 17:15:39.827938+07	f	test2			toa@gmail.com	f	t	2026-04-20 17:15:11.889291+07
11	pbkdf2_sha256$1200000$j3U7BZN49lk7LrkmOvY79H$MZcb2mXn154kuXEuUhiMQPyiYOs5vau4IIc90eWlDPc=	2026-04-20 17:21:55.968904+07	f	ttttt			naothinh74@gmail.com	f	t	2026-04-20 17:21:27.10393+07
10	pbkdf2_sha256$1200000$aISyW0v9PIU1O6YqrpR7V4$yv22RHb6WY+052RMbtfuEroyoG8L1Jxjd/Dc043hrVw=	2026-04-20 17:27:01.554676+07	f	test3			to232132t7@gmail.com	f	t	2026-04-20 17:17:59.920815+07
\.


--
-- TOC entry 6086 (class 0 OID 17550)
-- Dependencies: 238
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 6088 (class 0 OID 17559)
-- Dependencies: 240
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 6090 (class 0 OID 17620)
-- Dependencies: 242
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 6076 (class 0 OID 17490)
-- Dependencies: 228
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	restaurants	restaurant
8	restaurants	reservation
9	restaurants	table
10	restaurants	dish
11	restaurants	testmodel
12	restaurants	testmodel2
13	restaurants	feedback
14	restaurants	testuser
15	restaurants	restaurantimage
16	restaurants	pickuporder
17	restaurants	pickuporderitem
18	restaurants	reservationitem
19	restaurants	passwordresettoken
20	restaurants	userprofile
21	restaurants	restaurantintroduction
22	restaurants	amenitycategory
23	restaurants	restaurantamenity
\.


--
-- TOC entry 6074 (class 0 OID 17478)
-- Dependencies: 226
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-02-01 12:08:47.065766+07
2	auth	0001_initial	2026-02-01 12:08:47.102721+07
3	admin	0001_initial	2026-02-01 12:08:47.111825+07
4	admin	0002_logentry_remove_auto_add	2026-02-01 12:08:47.117677+07
5	admin	0003_logentry_add_action_flag_choices	2026-02-01 12:08:47.121072+07
6	contenttypes	0002_remove_content_type_name	2026-02-01 12:08:47.129022+07
7	auth	0002_alter_permission_name_max_length	2026-02-01 12:08:47.132955+07
8	auth	0003_alter_user_email_max_length	2026-02-01 12:08:47.136722+07
9	auth	0004_alter_user_username_opts	2026-02-01 12:08:47.139954+07
10	auth	0005_alter_user_last_login_null	2026-02-01 12:08:47.143585+07
11	auth	0006_require_contenttypes_0002	2026-02-01 12:08:47.144239+07
12	auth	0007_alter_validators_add_error_messages	2026-02-01 12:08:47.147497+07
13	auth	0008_alter_user_username_max_length	2026-02-01 12:08:47.152814+07
14	auth	0009_alter_user_last_name_max_length	2026-02-01 12:08:47.158629+07
15	auth	0010_alter_group_name_max_length	2026-02-01 12:08:47.163325+07
16	auth	0011_update_proxy_permissions	2026-02-01 12:08:47.167535+07
17	auth	0012_alter_user_first_name_max_length	2026-02-01 12:08:47.171327+07
18	sessions	0001_initial	2026-02-01 12:08:47.176066+07
26	restaurants	0007_testmodel_testmodel2	2026-03-30 12:57:40.235325+07
27	restaurants	0008_feedback_testuser_delete_testmodel_delete_testmodel2	2026-03-30 14:51:16.814289+07
30	restaurants	0007_testuser_feedback_restaurantimage	2026-04-06 01:28:31.694588+07
41	restaurants	0016_userprofile_passwordresettoken	2026-04-20 14:01:26.231485+07
42	restaurants	0017_restaurantintroduction	2026-04-20 14:23:30.935335+07
43	restaurants	0018_alter_restaurantintroduction_options_and_more	2026-04-20 14:44:14.565255+07
44	restaurants	0019_alter_restaurant_district	2026-04-20 14:44:46.070548+07
46	restaurants	0001_initial	2026-04-20 16:19:59.518381+07
47	restaurants	0002_restaurant_district_restaurant_image	2026-04-20 16:19:59.519772+07
48	restaurants	0003_dish	2026-04-20 16:19:59.520349+07
49	restaurants	0004_alter_restaurant_district	2026-04-20 16:19:59.520859+07
50	restaurants	0005_reservation_status	2026-04-20 16:19:59.521311+07
51	restaurants	0006_reservation_user	2026-04-20 16:19:59.521801+07
52	restaurants	0007_feedback_restaurantimage	2026-04-20 16:19:59.522471+07
53	restaurants	0008_alter_dish_id_alter_feedback_id_alter_reservation_id_and_more	2026-04-20 16:19:59.523208+07
54	restaurants	0009_dish_is_price_representative	2026-04-20 16:19:59.523689+07
55	restaurants	0010_reservation_queue_position_and_more	2026-04-20 16:19:59.524171+07
56	restaurants	0011_feedback_unique_feedback_email_per_restaurant	2026-04-20 16:19:59.524651+07
57	restaurants	0012_alter_dish_id_alter_feedback_id_alter_pickuporder_id_and_more	2026-04-20 16:19:59.52512+07
58	restaurants	0013_alter_dish_options_alter_feedback_options_and_more	2026-04-20 16:19:59.525967+07
59	restaurants	0014_alter_dish_id_alter_feedback_id_alter_pickuporder_id_and_more	2026-04-20 16:19:59.526647+07
60	restaurants	0015_add_reservation_item_and_updates	2026-04-20 16:19:59.527258+07
61	restaurants	0016_update_models	2026-04-20 16:20:17.339408+07
62	restaurants	0017_revert_district_max_length	2026-04-20 16:24:03.996753+07
63	restaurants	0020_delete_restaurantintroduction_and_more	2026-04-21 07:12:43.186977+07
64	restaurants	0021_restaurant_long_description	2026-04-21 07:12:43.202756+07
65	restaurants	0022_amenitycategory_restaurantamenity	2026-04-21 07:34:15.320371+07
66	restaurants	0023_merge_20260501_0759	2026-05-09 02:31:37.450033+07
\.


--
-- TOC entry 6091 (class 0 OID 17660)
-- Dependencies: 243
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
pmlvi2jzg8d8cd676mlckd8kd0g6uy0n	e30:1vo9Ox:xXjXDCgb8Zmznt7qaRpfGnoagEhqe7cz-a7ic_LDt3s	2026-02-20 07:08:47.641164+07
7n8xq6mqweytdk8rhs9hgi6z2rgnp218	e30:1vo9Qz:dLOBRSCx2I0yONx_sn3HBLVqGl05R2P2Uqoh_ys-IO8	2026-02-20 07:10:53.158841+07
mftjmdnx22mlc83i9k62z3ky0x2rxfyw	.eJxVjDsOwyAQBe-ydYQEGAOuovQ5A1rYtU0SQ-RPmih3jyy5cflmRu8Lby6UyxA-POc-J1xzLYEnzC_oAGnKRcnrsG-R6gQXCLitY9gWnkMm6ECeWcT05LILemAZqki1rHOOYk_EYRdxr8Sv29GeDkZcRuiArffaGdlKaw1G76z30aEnjCixJaUadsr00XJ0qXEmGdtoTRqJUo8Sfn-EYUnc:1wLQzS:z0gYJc4PUPzmbqeCdA-ZgjVWT9HB2TXoZBh_hqLKhf4	2026-05-23 02:36:02.320087+07
pww01ttfebkslh8wyqjo88ox8raud0uj	.eJxVjEEKwyAQAP-y5yKoMWqOvfcNsutuatqiEJNT6d9LIIf2OjPMGxLuW0l7lzUtDBNouPwywvyUegh-YL03lVvd1oXUkajTdnVrLK_r2f4NCvYCE4iP0QanR-29Q4rBx0gBIyOhxpGNGSQYN5MXCnkILjs_WMsWmfOMGj5f0ws4HQ:1vo9T4:4lW3BYDfSrfE50AhDVV3fukluHLp2O-RS07M6O5h8Fo	2026-02-20 07:13:02.957858+07
4wis02ygqot7i8eyty0buo9ch3xyskk2	.eJxVjEEKwyAQAP-y5yKoMWqOvfcNsutuatqiEJNT6d9LIIf2OjPMGxLuW0l7lzUtDBNouPwywvyUegh-YL03lVvd1oXUkajTdnVrLK_r2f4NCvYCE4iP0QanR-29Q4rBx0gBIyOhxpGNGSQYN5MXCnkILjs_WMsWmfOMGj5f0ws4HQ:1vyPYq:XL5egHD6tHmpKBP1JO4g7Weh9uC5YN9QmRmGw-Hlhws	2026-03-20 14:25:24.729501+07
gsjfylwxjm2moz0tvhm4mpbnves2b2li	.eJxVjEEKwyAQAP-y5yKoMWqOvfcNsutuatqiEJNT6d9LIIf2OjPMGxLuW0l7lzUtDBNouPwywvyUegh-YL03lVvd1oXUkajTdnVrLK_r2f4NCvYCE4iP0QanR-29Q4rBx0gBIyOhxpGNGSQYN5MXCnkILjs_WMsWmfOMGj5f0ws4HQ:1w75UY:EpKiZYTEaBhRO9Nf2YcXdI1bR1H58zbmSMvXqJ8nOtU	2026-04-13 12:48:50.498875+07
rb5ikd83kkvy7kl683w5u2f10xa9dc3w	.eJxVjEEKwyAQAP-y5yKoMWqOvfcNsutuatqiEJNT6d9LIIf2OjPMGxLuW0l7lzUtDBNouPwywvyUegh-YL03lVvd1oXUkajTdnVrLK_r2f4NCvYCE4iP0QanR-29Q4rBx0gBIyOhxpGNGSQYN5MXCnkILjs_WMsWmfOMGj5f0ws4HQ:1w9QnW:QiE1-99mZO2K3Uuhvqk3LdIeMSoXIeReeDIfbagDCMI	2026-04-19 23:58:06.407361+07
pioac5bnk74z6fsy0x3gitg65go7rq4t	.eJxVjEEKwyAQAP-y5yKoMWqOvfcNsutuatqiEJNT6d9LIIf2OjPMGxLuW0l7lzUtDBNouPwywvyUegh-YL03lVvd1oXUkajTdnVrLK_r2f4NCvYCE4iP0QanR-29Q4rBx0gBIyOhxpGNGSQYN5MXCnkILjs_WMsWmfOMGj5f0ws4HQ:1wF0uv:TaCV0KsCCsz5jPzxTeCNLxpHYuvT0Zq5J9mRoiXqwKM	2026-05-05 09:32:49.159029+07
\.


--
-- TOC entry 6117 (class 0 OID 18795)
-- Dependencies: 269
-- Data for Name: restaurants_amenitycategory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_amenitycategory (id, name, icon, description, "order") FROM stdin;
1	Free Wifi	fas fa-wifi	Quán cung cấp dịch vụ wifi miễn phí cho khách hàng	1
2	Máy lạnh	fas fa-snowflake	Quán có hệ thống điều hòa không khí để làm mát	2
3	Giữ xe	fas fa-parking	Quán cung cấp dịch vụ giữ xe miễn phí cho khách	3
4	Bàn hút khói	fas fa-fan	Quán có bàn hút khói cho khách hút thuốc	4
5	Toilet sạch	fas fa-restroom	Quán có nhà vệ sinh sạch sẽ và hiện đại	5
6	Đặt bàn trước	fas fa-calendar-alt	Quán cho phép khách đặt bàn trước	6
7	Giao hàng	fas fa-motorcycle	Quán cung cấp dịch vụ giao hàng đến tận nơi	7
8	Có bàn cao	fas fa-chair	Quán có bàn cao phù hợp cho làm việc hoặc chờ	8
9	Nhạc sống	fas fa-music	Quán có buổi biểu diễn âm nhạc sống	9
10	Phòng VIP	fas fa-crown	Quán có phòng riêng biệt cho nhóm lớn hoặc VIP	10
\.


--
-- TOC entry 6099 (class 0 OID 17738)
-- Dependencies: 251
-- Data for Name: restaurants_dish; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_dish (id, name, description, price, image, is_available, restaurant_id, is_price_representative, created_at) FROM stdin;
39	Bánh Cuốn Đặc Biệt		35000		f	20	f	2026-04-20 07:23:13.295527+07
94	Phở Bò	Phở bò nóng với nước dùng thơm ngon	50000		t	20	t	2026-04-21 09:39:07.900432+07
95	Gà Rán Giòn	Gà rán giòn sốt cà chua chua ngon	45000		t	20	f	2026-04-21 09:39:07.90829+07
26	Bánh Mì Đặc Biệt		68000		t	14	f	2026-04-20 07:23:13.295527+07
27	Chả Lụa (100g)		40000	dishes/photo-1565557623262-b51c2513a641_BBBBqK4.jpg	t	14	f	2026-04-20 07:23:13.295527+07
28	Pizza 4 Cheese		280000	dishes/photo-1513104890138-7c749659a591_TWYVhvA.jpg	t	15	f	2026-04-20 07:23:13.295527+07
29	Mì Ý Cua		250000	dishes/photo-1563379926898-05f4575a45d8_lVYILEU.jpg	t	15	f	2026-04-20 07:23:13.295527+07
30	Trà Sữa Chôm Chôm		55000	dishes/photo-1559496417-e7f25cb247f3_GXy9GIR.jpg	t	16	f	2026-04-20 07:23:13.295527+07
31	Cà Phê Sữa Đá		45000	dishes/photo-1578314675249-a6910f80cc4e_LPB4Av9.jpg	t	16	f	2026-04-20 07:23:13.295527+07
32	Há Cảo Tôm		68000	dishes/photo-1563245372-f21724e3856d_HMnmtYS.jpg	t	17	f	2026-04-20 07:23:13.295527+07
33	Bánh Bao Kim Sa		55000	dishes/photo-1615937657715-bc7b4b7962c1_vLckxU9.jpg	t	17	f	2026-04-20 07:23:13.295527+07
34	Vịt Quay Bắc Kinh		450000	dishes/photo-1579888944880-d98341245702_btFlgxz.jpg	t	17	f	2026-04-20 07:23:13.295527+07
35	Cơm Sườn Bì Chả		85000		t	18	f	2026-04-20 07:23:13.295527+07
36	Cơm Sườn Cây		110000	dishes/photo-1626082927389-6cd097cdc6ec_VpOA4ca.jpg	t	18	f	2026-04-20 07:23:13.295527+07
37	Gà Nướng		160000	dishes/photo-1606728035253-49e8a23146de_hpOJ44L.jpg	t	19	f	2026-04-20 07:23:13.295527+07
38	Bánh Mì Mật Ong		5000	dishes/photo-1550547660-d9450f859349_4QQLN2x.jpg	t	19	f	2026-04-20 07:23:13.295527+07
96	Cơm Tấm Sườn Nướng	Cơm tấm, sườn nướng, ăn kèm dưa leo và trứng	35000		t	20	f	2026-04-21 09:39:07.909617+07
\.


--
-- TOC entry 6103 (class 0 OID 17829)
-- Dependencies: 255
-- Data for Name: restaurants_feedback; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_feedback (id, customer_name, customer_email, rating, message, created_at, is_read, restaurant_id) FROM stdin;
1	toan	toanchaut7@gmail.com	5	ok	2026-04-21 09:35:07.975294+07	t	19
\.


--
-- TOC entry 6115 (class 0 OID 18718)
-- Dependencies: 267
-- Data for Name: restaurants_passwordresettoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_passwordresettoken (id, token, expires_at, is_used, created_at, user_id) FROM stdin;
1	98e1744fbc09a3c9386ad0a646eafe20e7a47d4f8d96ccdc41d5c4fc315c80c0	2026-04-20 15:06:15.937206+07	f	2026-04-20 14:06:15.937669+07	1
2	54de8ffe019b0a166024a3a300409ea474d33cd69dc02e7cf855e83de6ac3aac	2026-04-20 15:06:38.241607+07	f	2026-04-20 14:06:38.241902+07	6
3	ee06d944587e25833273ac628a51ae424bec91e713f205dd84e806485dc3892a	2026-04-20 18:22:29.531342+07	t	2026-04-20 17:22:29.531535+07	11
4	9cc89673c9c32b40ea0f349b0938b29679400b560bed4bb1a70dde62aedfe673	2026-04-21 07:43:26.960745+07	f	2026-04-21 06:43:26.960975+07	12
5	70d28c5edb508ae3e2d12c48de1e7dd577cbb5b8a8647e4cb3150243fba5f97f	2026-04-21 10:30:48.804513+07	t	2026-04-21 09:30:48.804839+07	13
\.


--
-- TOC entry 6107 (class 0 OID 18006)
-- Dependencies: 259
-- Data for Name: restaurants_pickuporder; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_pickuporder (id, customer_name, customer_phone, pickup_time, note, status, created_at, restaurant_id, user_id) FROM stdin;
\.


--
-- TOC entry 6109 (class 0 OID 18022)
-- Dependencies: 261
-- Data for Name: restaurants_pickuporderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_pickuporderitem (id, quantity, dish_id, pickup_order_id) FROM stdin;
\.


--
-- TOC entry 6097 (class 0 OID 17711)
-- Dependencies: 249
-- Data for Name: restaurants_reservation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_reservation (id, customer_name, booking_time, number_of_people, table_id, status, user_id, queue_position, created_at, customer_phone, note, updated_at) FROM stdin;
6	rtsesadas	2026-02-28 14:54:00+07	2	79	cancelled	1	0	2026-04-20 07:23:13.332948+07			2026-04-20 08:09:31.646699+07
5	CPU	2026-02-28 14:54:00+07	4	79	cancelled	\N	0	2026-04-20 07:23:13.332948+07			2026-04-20 08:09:31.646699+07
3	dsada	2026-02-14 14:26:00+07	4	89	cancelled	\N	0	2026-04-20 07:23:13.332948+07			2026-04-20 08:22:55.025786+07
9	dsadsad	2026-05-01 18:10:00+07	4	103	cancelled	\N	0	2026-04-20 08:11:04.96041+07			2026-04-20 08:23:04.636519+07
8	dsadsa	2026-03-31 03:45:00+07	2	59	cancelled	4	0	2026-04-20 07:23:13.332948+07			2026-04-20 08:23:10.885493+07
7	Toaan	2026-03-13 21:25:00+07	2	79	cancelled	5	0	2026-04-20 07:23:13.332948+07			2026-04-20 08:23:15.490347+07
4	CPU	2026-02-28 14:54:00+07	4	79	cancelled	\N	0	2026-04-20 07:23:13.332948+07			2026-04-20 08:23:24.39065+07
\.


--
-- TOC entry 6111 (class 0 OID 18678)
-- Dependencies: 263
-- Data for Name: restaurants_reservationitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_reservationitem (id, quantity, created_at, dish_id, reservation_id) FROM stdin;
\.


--
-- TOC entry 6093 (class 0 OID 17687)
-- Dependencies: 245
-- Data for Name: restaurants_restaurant; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_restaurant (id, name, address, location, created_at, district, image, is_pickup_available, description, long_description) FROM stdin;
20	Bánh Cuốn Nóng Ngọc Mỹ	Kiot 44 Chợ Hạnh Thông Tây	0101000020E6100000AE47E17A14AA5A405EBA490C02AB2540	2026-02-05 19:44:34.210494+07	GV	restaurant_images/vn-11134259-7r98o-lwfu88v4o2jd2dresize_ss640x400.jfif	f	Nhà hàng Bánh Cuốn Nóng Ngọc Mỹ nổi tiếng tại Gò Vấp	Nhà hàng Bánh Cuốn Nóng Ngọc Mỹ là một địa chỉ ưa thích tại Gò Vấp, TP.HCM.\r\n\r\nQuán cung cấp các món ăn ngon, chất lượng cao với dịch vụ tận tình.\r\nKhông gian quán thoáng mát, sạch sẽ, phù hợp cho ăn gia đình hoặc tập thể.\r\nQuán chào đón khách hàng hàng ngày từ sáng đến tối.\r\n\r\nVui lòng liên hệ quán để biết thêm chi tiết về menu và các dịch vụ khác.
21	Quán Cơm Tăng Kí	17 đường số 7, Gò Vấp	0101000020E610000031F9556FC3AB5A40972B723E2BA72540	2026-03-06 15:43:04.893261+07	GV	restaurant_images/unnamed_2.jpg	f	Nhà hàng Quán Cơm Tăng Kí nổi tiếng tại Gò Vấp	Nhà hàng Quán Cơm Tăng Kí là một địa chỉ ưa thích tại Gò Vấp, TP.HCM.\r\n\r\nQuán cung cấp các món ăn ngon, chất lượng cao với dịch vụ tận tình.\r\nKhông gian quán thoáng mát, sạch sẽ, phù hợp cho ăn gia đình hoặc tập thể.\r\nQuán chào đón khách hàng hàng ngày từ sáng đến tối.\r\n\r\nVui lòng liên hệ quán để biết thêm chi tiết về menu và các dịch vụ khác.
18	Cơm Tấm Ba Ghiền	84 Đặng Văn Ngữ, P.10	0101000020E610000073D712F241AB5A409A779CA223992540	2026-02-05 19:44:31.523544+07	PN	restaurant_images/unnamed.jpg	f	Nhà hàng Cơm Tấm Ba Ghiền nổi tiếng tại Phú Nhuận	Nhà hàng Cơm Tấm Ba Ghiền là một địa chỉ ưa thích tại Phú Nhuận, TP.HCM.\n\nQuán cung cấp các món ăn ngon, chất lượng cao với dịch vụ tận tình.\nKhông gian quán thoáng mát, sạch sẽ, phù hợp cho ăn gia đình hoặc tập thể.\nQuán chào đón khách hàng hàng ngày từ sáng đến tối.\n\nVui lòng liên hệ quán để biết thêm chi tiết về menu và các dịch vụ khác.
16	Katinat Saigon Kafe	91 Đồng Khởi, P. Bến Nghé	0101000020E610000005A3923A01AD5A403E7958A8358D2540	2026-02-05 19:44:29.128519+07	1	restaurant_images/photo-1559496417-e7f25cb247f3_ZfxLsAU.jpg	f	Nhà hàng Katinat Saigon Kafe nổi tiếng tại Quận 1	Nhà hàng Katinat Saigon Kafe là một địa chỉ ưa thích tại Quận 1, TP.HCM.\n\nQuán cung cấp các món ăn ngon, chất lượng cao với dịch vụ tận tình.\nKhông gian quán thoáng mát, sạch sẽ, phù hợp cho ăn gia đình hoặc tập thể.\nQuán chào đón khách hàng hàng ngày từ sáng đến tối.\n\nVui lòng liên hệ quán để biết thêm chi tiết về menu và các dịch vụ khác.
15	Pizza 4P's Bến Thành	8 Thủ Khoa Huân, P. Bến Thành	0101000020E6100000E9263108ACAC5A40EC51B81E858B2540	2026-02-05 19:44:28.160618+07	1	restaurant_images/photo-1574071318508-1cdbab80d002_zlgrxFh.jpg	f	Nhà hàng Pizza 4P's Bến Thành nổi tiếng tại Quận 1	Nhà hàng Pizza 4P's Bến Thành là một địa chỉ ưa thích tại Quận 1, TP.HCM.\n\nQuán cung cấp các món ăn ngon, chất lượng cao với dịch vụ tận tình.\nKhông gian quán thoáng mát, sạch sẽ, phù hợp cho ăn gia đình hoặc tập thể.\nQuán chào đón khách hàng hàng ngày từ sáng đến tối.\n\nVui lòng liên hệ quán để biết thêm chi tiết về menu và các dịch vụ khác.
14	Bánh Mì Huỳnh Hoa	26 Lê Thị Riêng, P. Phạm Ngũ Lão	0101000020E61000008638D6C56DAC5A405EBA490C028B2540	2026-02-05 19:44:26.507758+07	1	restaurant_images/unnamed_1.jpg	f	Nhà hàng Bánh Mì Huỳnh Hoa nổi tiếng tại Quận 1	Nhà hàng Bánh Mì Huỳnh Hoa là một địa chỉ ưa thích tại Quận 1, TP.HCM.\n\nQuán cung cấp các món ăn ngon, chất lượng cao với dịch vụ tận tình.\nKhông gian quán thoáng mát, sạch sẽ, phù hợp cho ăn gia đình hoặc tập thể.\nQuán chào đón khách hàng hàng ngày từ sáng đến tối.\n\nVui lòng liên hệ quán để biết thêm chi tiết về menu và các dịch vụ khác.
19	Gà Nướng Anh Tư	449 Lê Quang Định, P.5	0101000020E61000001CEBE2361AAC5A40C3D32B6519A22540	2026-02-05 19:44:33.206252+07	BT	restaurant_images/photo-1606728035253-49e8a23146de_QpOAwvl.jpg	f	Nhà hàng Gà Nướng Anh Tư nổi tiếng tại Bình Thạnh	Nhà hàng Gà Nướng Anh Tư là một địa chỉ ưa thích tại Bình Thạnh, TP.HCM.\r\n\r\nQuán cung cấp các món ăn ngon, chất lượng cao với dịch vụ tận tình.\r\nKhông gian quán thoáng mát, sạch sẽ, phù hợp cho ăn gia đình hoặc tập thể.\r\nQuán chào đón khách hàng hàng ngày từ sáng đến tối.\r\n\r\nVui lòng liên hệ quán để biết thêm chi tiết về menu và các dịch vụ khác.
17	Dim Tu Tac (Dimsum)	29B Trần Hưng Đạo, P.6	0101000020E6100000BADA8AFD65AB5A401973D712F2812540	2026-02-05 19:44:30.140448+07	5	restaurant_images/photo-1563245372-f21724e3856d_T8Z1kkF.jpg	f	Nhà hàng Dim Tu Tac (Dimsum) nổi tiếng tại Quận 5	Nhà hàng Dim Tu Tac (Dimsum) là một địa chỉ ưa thích tại Quận 5, TP.HCM.\r\n\r\nQuán cung cấp các món ăn ngon, chất lượng cao với dịch vụ tận tình.\r\nKhông gian quán thoáng mát, sạch sẽ, phù hợp cho ăn gia đình hoặc tập thể.\r\nQuán chào đón khách hàng hàng ngày từ sáng đến tối.\r\n\r\nVui lòng liên hệ quán để biết thêm chi tiết về menu và các dịch vụ khác.
\.


--
-- TOC entry 6119 (class 0 OID 18810)
-- Dependencies: 271
-- Data for Name: restaurants_restaurantamenity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_restaurantamenity (id, is_available, note, category_id, restaurant_id) FROM stdin;
9	t		1	19
10	t		3	19
11	t		4	19
12	t		7	19
13	t		1	17
14	t		2	17
15	t		3	17
16	t		4	17
17	t		5	17
18	t		6	17
19	t		8	17
20	t		10	17
21	t		1	20
22	t		3	20
23	t		7	20
24	t		1	21
25	t		3	21
26	t		5	21
27	t		8	21
\.


--
-- TOC entry 6105 (class 0 OID 17845)
-- Dependencies: 257
-- Data for Name: restaurants_restaurantimage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_restaurantimage (id, image, created_at, restaurant_id) FROM stdin;
6	restaurant_gallery/balo-da-nam-local-brand-2.webp	2026-04-21 09:40:08.30806+07	21
7	restaurant_gallery/balo-di-hoc-local-brand-da-mau-den-davies-7-e3736f2e-633e-423c-a0a9-_ghod8xB.webp	2026-04-21 09:40:08.310712+07	21
8	restaurant_gallery/balo-local-brand-di-hoc-nam-nu-da-mau-den-1-2b0de8ff-4cc6-4acb-94fa-_1xKoKG1.webp	2026-04-21 09:40:08.31223+07	21
\.


--
-- TOC entry 6095 (class 0 OID 17700)
-- Dependencies: 247
-- Data for Name: restaurants_table; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_table (id, table_number, capacity, is_available, restaurant_id) FROM stdin;
39	Bàn 1	2	t	14
40	Bàn 2	2	t	14
41	Bàn 3	2	t	14
42	Bàn 4	2	t	14
43	Bàn 5	4	t	14
44	Bàn 6	4	t	14
45	Bàn 7	4	t	14
46	Bàn 8	4	t	14
47	Bàn 9	10	t	14
48	Bàn 10	10	t	14
49	Bàn 1	2	t	15
50	Bàn 2	2	t	15
51	Bàn 3	2	t	15
52	Bàn 4	2	t	15
53	Bàn 5	4	t	15
54	Bàn 6	4	t	15
55	Bàn 7	4	t	15
56	Bàn 8	4	t	15
57	Bàn 9	10	t	15
58	Bàn 10	10	t	15
59	Bàn 1	2	t	16
60	Bàn 2	2	t	16
61	Bàn 3	2	t	16
62	Bàn 4	2	t	16
63	Bàn 5	4	t	16
64	Bàn 6	4	t	16
65	Bàn 7	4	t	16
66	Bàn 8	4	t	16
67	Bàn 9	10	t	16
68	Bàn 10	10	t	16
69	Bàn 1	2	t	17
70	Bàn 2	2	t	17
71	Bàn 3	2	t	17
72	Bàn 4	2	t	17
73	Bàn 5	4	t	17
74	Bàn 6	4	t	17
75	Bàn 7	4	t	17
76	Bàn 8	4	t	17
77	Bàn 9	10	t	17
78	Bàn 10	10	t	17
79	Bàn 1	2	t	18
80	Bàn 2	2	t	18
81	Bàn 3	2	t	18
82	Bàn 4	2	t	18
83	Bàn 5	4	t	18
84	Bàn 6	4	t	18
85	Bàn 7	4	t	18
86	Bàn 8	4	t	18
87	Bàn 9	10	t	18
88	Bàn 10	10	t	18
90	Bàn 2	2	t	19
91	Bàn 3	2	t	19
92	Bàn 4	2	t	19
93	Bàn 5	4	t	19
94	Bàn 6	4	t	19
95	Bàn 7	4	t	19
96	Bàn 8	4	t	19
97	Bàn 9	10	t	19
98	Bàn 10	10	t	19
99	Bàn 1	2	t	20
100	Bàn 2	2	t	20
101	Bàn 3	2	t	20
102	Bàn 4	2	t	20
103	Bàn 5	4	t	20
104	Bàn 6	4	t	20
105	Bàn 7	4	t	20
106	Bàn 8	4	t	20
107	Bàn 9	10	t	20
108	Bàn 10	10	t	20
89	Bàn 1	2	f	19
121	Bàn 1	4	t	21
122	Bàn 2	4	t	21
123	Bàn 3	4	t	21
124	Bàn 4	8	t	21
\.


--
-- TOC entry 6101 (class 0 OID 17809)
-- Dependencies: 253
-- Data for Name: restaurants_testuser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_testuser (id, name) FROM stdin;
\.


--
-- TOC entry 6113 (class 0 OID 18704)
-- Dependencies: 265
-- Data for Name: restaurants_userprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_userprofile (id, email_verified, email_verification_token, email_verification_expires, created_at, updated_at, user_id) FROM stdin;
1	t		\N	2026-04-20 14:02:32.331541+07	2026-04-20 14:03:19.522309+07	6
2	t		\N	2026-04-20 17:09:26.327234+07	2026-04-20 17:12:34.314183+07	7
3	t		\N	2026-04-20 17:13:16.281881+07	2026-04-20 17:13:44.962833+07	8
4	t		\N	2026-04-20 17:15:12.329606+07	2026-04-20 17:15:28.104825+07	9
5	t		\N	2026-04-20 17:18:00.377288+07	2026-04-20 17:18:21.370298+07	10
6	t		\N	2026-04-20 17:21:27.540774+07	2026-04-20 17:21:41.546792+07	11
7	t		\N	2026-04-21 06:41:57.932396+07	2026-04-21 06:42:30.827999+07	12
8	t		\N	2026-04-21 09:30:06.82565+07	2026-04-21 09:30:21.717348+07	13
9	t		\N	2026-05-09 02:32:57.44516+07	2026-05-09 02:32:57.447444+07	14
\.


--
-- TOC entry 5781 (class 0 OID 16708)
-- Dependencies: 221
-- Data for Name: spatial_ref_sys; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.spatial_ref_sys (srid, auth_name, auth_srid, srtext, proj4text) FROM stdin;
\.


--
-- TOC entry 6126 (class 0 OID 0)
-- Dependencies: 231
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 6127 (class 0 OID 0)
-- Dependencies: 233
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 6128 (class 0 OID 0)
-- Dependencies: 229
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 92, true);


--
-- TOC entry 6129 (class 0 OID 0)
-- Dependencies: 237
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- TOC entry 6130 (class 0 OID 0)
-- Dependencies: 235
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 14, true);


--
-- TOC entry 6131 (class 0 OID 0)
-- Dependencies: 239
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 6132 (class 0 OID 0)
-- Dependencies: 241
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 6133 (class 0 OID 0)
-- Dependencies: 227
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 23, true);


--
-- TOC entry 6134 (class 0 OID 0)
-- Dependencies: 225
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 66, true);


--
-- TOC entry 6135 (class 0 OID 0)
-- Dependencies: 268
-- Name: restaurants_amenitycategory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_amenitycategory_id_seq', 10, true);


--
-- TOC entry 6136 (class 0 OID 0)
-- Dependencies: 250
-- Name: restaurants_dish_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_dish_id_seq', 96, true);


--
-- TOC entry 6137 (class 0 OID 0)
-- Dependencies: 254
-- Name: restaurants_feedback_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_feedback_id_seq', 1, true);


--
-- TOC entry 6138 (class 0 OID 0)
-- Dependencies: 266
-- Name: restaurants_passwordresettoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_passwordresettoken_id_seq', 5, true);


--
-- TOC entry 6139 (class 0 OID 0)
-- Dependencies: 258
-- Name: restaurants_pickuporder_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_pickuporder_id_seq', 1, false);


--
-- TOC entry 6140 (class 0 OID 0)
-- Dependencies: 260
-- Name: restaurants_pickuporderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_pickuporderitem_id_seq', 1, false);


--
-- TOC entry 6141 (class 0 OID 0)
-- Dependencies: 248
-- Name: restaurants_reservation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_reservation_id_seq', 9, true);


--
-- TOC entry 6142 (class 0 OID 0)
-- Dependencies: 262
-- Name: restaurants_reservationitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_reservationitem_id_seq', 1, false);


--
-- TOC entry 6143 (class 0 OID 0)
-- Dependencies: 244
-- Name: restaurants_restaurant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_restaurant_id_seq', 36, true);


--
-- TOC entry 6144 (class 0 OID 0)
-- Dependencies: 270
-- Name: restaurants_restaurantamenity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_restaurantamenity_id_seq', 27, true);


--
-- TOC entry 6145 (class 0 OID 0)
-- Dependencies: 256
-- Name: restaurants_restaurantimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_restaurantimage_id_seq', 8, true);


--
-- TOC entry 6146 (class 0 OID 0)
-- Dependencies: 246
-- Name: restaurants_table_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_table_id_seq', 124, true);


--
-- TOC entry 6147 (class 0 OID 0)
-- Dependencies: 252
-- Name: restaurants_testuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_testuser_id_seq', 1, false);


--
-- TOC entry 6148 (class 0 OID 0)
-- Dependencies: 264
-- Name: restaurants_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_userprofile_id_seq', 9, true);


--
-- TOC entry 5804 (class 2606 OID 17656)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 5809 (class 2606 OID 17577)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 5812 (class 2606 OID 17529)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5806 (class 2606 OID 17518)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 5799 (class 2606 OID 17568)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 5801 (class 2606 OID 17510)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 5820 (class 2606 OID 17557)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 5823 (class 2606 OID 17592)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 5814 (class 2606 OID 17546)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 5826 (class 2606 OID 17566)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5829 (class 2606 OID 17606)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 5817 (class 2606 OID 17649)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 5832 (class 2606 OID 17633)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 5794 (class 2606 OID 17500)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 5796 (class 2606 OID 17498)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 5792 (class 2606 OID 17488)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5836 (class 2606 OID 17669)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 5887 (class 2606 OID 18808)
-- Name: restaurants_amenitycategory restaurants_amenitycategory_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_amenitycategory
    ADD CONSTRAINT restaurants_amenitycategory_name_key UNIQUE (name);


--
-- TOC entry 5889 (class 2606 OID 18806)
-- Name: restaurants_amenitycategory restaurants_amenitycategory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_amenitycategory
    ADD CONSTRAINT restaurants_amenitycategory_pkey PRIMARY KEY (id);


--
-- TOC entry 5849 (class 2606 OID 18469)
-- Name: restaurants_dish restaurants_dish_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_dish
    ADD CONSTRAINT restaurants_dish_pkey PRIMARY KEY (id);


--
-- TOC entry 5854 (class 2606 OID 18494)
-- Name: restaurants_feedback restaurants_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_feedback
    ADD CONSTRAINT restaurants_feedback_pkey PRIMARY KEY (id);


--
-- TOC entry 5880 (class 2606 OID 18728)
-- Name: restaurants_passwordresettoken restaurants_passwordresettoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_passwordresettoken
    ADD CONSTRAINT restaurants_passwordresettoken_pkey PRIMARY KEY (id);


--
-- TOC entry 5883 (class 2606 OID 18730)
-- Name: restaurants_passwordresettoken restaurants_passwordresettoken_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_passwordresettoken
    ADD CONSTRAINT restaurants_passwordresettoken_token_key UNIQUE (token);


--
-- TOC entry 5862 (class 2606 OID 18507)
-- Name: restaurants_pickuporder restaurants_pickuporder_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_pickuporder
    ADD CONSTRAINT restaurants_pickuporder_pkey PRIMARY KEY (id);


--
-- TOC entry 5868 (class 2606 OID 18533)
-- Name: restaurants_pickuporderitem restaurants_pickuporderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_pickuporderitem
    ADD CONSTRAINT restaurants_pickuporderitem_pkey PRIMARY KEY (id);


--
-- TOC entry 5845 (class 2606 OID 18544)
-- Name: restaurants_reservation restaurants_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_reservation
    ADD CONSTRAINT restaurants_reservation_pkey PRIMARY KEY (id);


--
-- TOC entry 5870 (class 2606 OID 18765)
-- Name: restaurants_reservationitem restaurants_reservationi_reservation_id_dish_id_b3965f83_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_reservationitem
    ADD CONSTRAINT restaurants_reservationi_reservation_id_dish_id_b3965f83_uniq UNIQUE (reservation_id, dish_id);


--
-- TOC entry 5873 (class 2606 OID 18688)
-- Name: restaurants_reservationitem restaurants_reservationitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_reservationitem
    ADD CONSTRAINT restaurants_reservationitem_pkey PRIMARY KEY (id);


--
-- TOC entry 5840 (class 2606 OID 18555)
-- Name: restaurants_restaurant restaurants_restaurant_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_restaurant
    ADD CONSTRAINT restaurants_restaurant_pkey PRIMARY KEY (id);


--
-- TOC entry 5891 (class 2606 OID 18824)
-- Name: restaurants_restaurantamenity restaurants_restaurantam_restaurant_id_category_i_f94befca_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_restaurantamenity
    ADD CONSTRAINT restaurants_restaurantam_restaurant_id_category_i_f94befca_uniq UNIQUE (restaurant_id, category_id);


--
-- TOC entry 5894 (class 2606 OID 18821)
-- Name: restaurants_restaurantamenity restaurants_restaurantamenity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_restaurantamenity
    ADD CONSTRAINT restaurants_restaurantamenity_pkey PRIMARY KEY (id);


--
-- TOC entry 5859 (class 2606 OID 18637)
-- Name: restaurants_restaurantimage restaurants_restaurantimage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_restaurantimage
    ADD CONSTRAINT restaurants_restaurantimage_pkey PRIMARY KEY (id);


--
-- TOC entry 5842 (class 2606 OID 18647)
-- Name: restaurants_table restaurants_table_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_table
    ADD CONSTRAINT restaurants_table_pkey PRIMARY KEY (id);


--
-- TOC entry 5852 (class 2606 OID 17815)
-- Name: restaurants_testuser restaurants_testuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_testuser
    ADD CONSTRAINT restaurants_testuser_pkey PRIMARY KEY (id);


--
-- TOC entry 5876 (class 2606 OID 18714)
-- Name: restaurants_userprofile restaurants_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_userprofile
    ADD CONSTRAINT restaurants_userprofile_pkey PRIMARY KEY (id);


--
-- TOC entry 5878 (class 2606 OID 18716)
-- Name: restaurants_userprofile restaurants_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_userprofile
    ADD CONSTRAINT restaurants_userprofile_user_id_key UNIQUE (user_id);


--
-- TOC entry 5857 (class 2606 OID 18575)
-- Name: restaurants_feedback unique_feedback_email_per_restaurant; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_feedback
    ADD CONSTRAINT unique_feedback_email_per_restaurant UNIQUE (restaurant_id, customer_email);


--
-- TOC entry 5802 (class 1259 OID 17657)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 5807 (class 1259 OID 17588)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 5810 (class 1259 OID 17589)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 5797 (class 1259 OID 17574)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 5818 (class 1259 OID 17604)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 5821 (class 1259 OID 17603)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 5824 (class 1259 OID 17618)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 5827 (class 1259 OID 17617)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 5815 (class 1259 OID 17650)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 5830 (class 1259 OID 17644)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 5833 (class 1259 OID 17645)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 5834 (class 1259 OID 17671)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 5837 (class 1259 OID 17670)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 5885 (class 1259 OID 18822)
-- Name: restaurants_amenitycategory_name_e1206ba5_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_amenitycategory_name_e1206ba5_like ON public.restaurants_amenitycategory USING btree (name varchar_pattern_ops);


--
-- TOC entry 5850 (class 1259 OID 18565)
-- Name: restaurants_dish_restaurant_id_08f0a679; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_dish_restaurant_id_08f0a679 ON public.restaurants_dish USING btree (restaurant_id);


--
-- TOC entry 5855 (class 1259 OID 18576)
-- Name: restaurants_feedback_restaurant_id_b5627567; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_feedback_restaurant_id_b5627567 ON public.restaurants_feedback USING btree (restaurant_id);


--
-- TOC entry 5881 (class 1259 OID 18741)
-- Name: restaurants_passwordresettoken_token_e30f0183_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_passwordresettoken_token_e30f0183_like ON public.restaurants_passwordresettoken USING btree (token varchar_pattern_ops);


--
-- TOC entry 5884 (class 1259 OID 18742)
-- Name: restaurants_passwordresettoken_user_id_dbaa53d2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_passwordresettoken_user_id_dbaa53d2 ON public.restaurants_passwordresettoken USING btree (user_id);


--
-- TOC entry 5863 (class 1259 OID 18593)
-- Name: restaurants_pickuporder_restaurant_id_715cd797; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_pickuporder_restaurant_id_715cd797 ON public.restaurants_pickuporder USING btree (restaurant_id);


--
-- TOC entry 5864 (class 1259 OID 18043)
-- Name: restaurants_pickuporder_user_id_ce796a31; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_pickuporder_user_id_ce796a31 ON public.restaurants_pickuporder USING btree (user_id);


--
-- TOC entry 5865 (class 1259 OID 18479)
-- Name: restaurants_pickuporderitem_dish_id_65d5afd6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_pickuporderitem_dish_id_65d5afd6 ON public.restaurants_pickuporderitem USING btree (dish_id);


--
-- TOC entry 5866 (class 1259 OID 18518)
-- Name: restaurants_pickuporderitem_pickup_order_id_d76481cc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_pickuporderitem_pickup_order_id_d76481cc ON public.restaurants_pickuporderitem USING btree (pickup_order_id);


--
-- TOC entry 5846 (class 1259 OID 18655)
-- Name: restaurants_reservation_table_id_2ac0dd3f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_reservation_table_id_2ac0dd3f ON public.restaurants_reservation USING btree (table_id);


--
-- TOC entry 5847 (class 1259 OID 17772)
-- Name: restaurants_reservation_user_id_1018ff81; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_reservation_user_id_1018ff81 ON public.restaurants_reservation USING btree (user_id);


--
-- TOC entry 5871 (class 1259 OID 18701)
-- Name: restaurants_reservationitem_dish_id_8f450452; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_reservationitem_dish_id_8f450452 ON public.restaurants_reservationitem USING btree (dish_id);


--
-- TOC entry 5874 (class 1259 OID 18702)
-- Name: restaurants_reservationitem_reservation_id_4c05e284; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_reservationitem_reservation_id_4c05e284 ON public.restaurants_reservationitem USING btree (reservation_id);


--
-- TOC entry 5838 (class 1259 OID 17721)
-- Name: restaurants_restaurant_location_aa827877_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_restaurant_location_aa827877_id ON public.restaurants_restaurant USING gist (location);


--
-- TOC entry 5892 (class 1259 OID 18835)
-- Name: restaurants_restaurantamenity_category_id_b0d5e9b0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_restaurantamenity_category_id_b0d5e9b0 ON public.restaurants_restaurantamenity USING btree (category_id);


--
-- TOC entry 5895 (class 1259 OID 18836)
-- Name: restaurants_restaurantamenity_restaurant_id_37c5d4e0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_restaurantamenity_restaurant_id_37c5d4e0 ON public.restaurants_restaurantamenity USING btree (restaurant_id);


--
-- TOC entry 5860 (class 1259 OID 18586)
-- Name: restaurants_restaurantimage_restaurant_id_395a3a59; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_restaurantimage_restaurant_id_395a3a59 ON public.restaurants_restaurantimage USING btree (restaurant_id);


--
-- TOC entry 5843 (class 1259 OID 18603)
-- Name: restaurants_table_restaurant_id_0a055aef; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_table_restaurant_id_0a055aef ON public.restaurants_table USING btree (restaurant_id);


--
-- TOC entry 5897 (class 2606 OID 17583)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5898 (class 2606 OID 17578)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5896 (class 2606 OID 17569)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5899 (class 2606 OID 17598)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5900 (class 2606 OID 17593)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5901 (class 2606 OID 17612)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5902 (class 2606 OID 17607)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5903 (class 2606 OID 17634)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5904 (class 2606 OID 17639)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5908 (class 2606 OID 18610)
-- Name: restaurants_dish restaurants_dish_restaurant_id_08f0a679_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_dish
    ADD CONSTRAINT restaurants_dish_restaurant_id_08f0a679_fk FOREIGN KEY (restaurant_id) REFERENCES public.restaurants_restaurant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5909 (class 2606 OID 18615)
-- Name: restaurants_feedback restaurants_feedback_restaurant_id_b5627567_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_feedback
    ADD CONSTRAINT restaurants_feedback_restaurant_id_b5627567_fk FOREIGN KEY (restaurant_id) REFERENCES public.restaurants_restaurant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5918 (class 2606 OID 18736)
-- Name: restaurants_passwordresettoken restaurants_passwordresettoken_user_id_dbaa53d2_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_passwordresettoken
    ADD CONSTRAINT restaurants_passwordresettoken_user_id_dbaa53d2_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5911 (class 2606 OID 18625)
-- Name: restaurants_pickuporder restaurants_pickuporder_restaurant_id_715cd797_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_pickuporder
    ADD CONSTRAINT restaurants_pickuporder_restaurant_id_715cd797_fk FOREIGN KEY (restaurant_id) REFERENCES public.restaurants_restaurant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5912 (class 2606 OID 18037)
-- Name: restaurants_pickuporder restaurants_pickuporder_user_id_ce796a31_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_pickuporder
    ADD CONSTRAINT restaurants_pickuporder_user_id_ce796a31_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5913 (class 2606 OID 18487)
-- Name: restaurants_pickuporderitem restaurants_pickuporderitem_dish_id_65d5afd6_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_pickuporderitem
    ADD CONSTRAINT restaurants_pickuporderitem_dish_id_65d5afd6_fk FOREIGN KEY (dish_id) REFERENCES public.restaurants_dish(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5914 (class 2606 OID 18526)
-- Name: restaurants_pickuporderitem restaurants_pickuporderitem_pickup_order_id_d76481cc_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_pickuporderitem
    ADD CONSTRAINT restaurants_pickuporderitem_pickup_order_id_d76481cc_fk FOREIGN KEY (pickup_order_id) REFERENCES public.restaurants_pickuporder(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5915 (class 2606 OID 18691)
-- Name: restaurants_reservationitem restaurants_reservat_dish_id_8f450452_fk_restauran; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_reservationitem
    ADD CONSTRAINT restaurants_reservat_dish_id_8f450452_fk_restauran FOREIGN KEY (dish_id) REFERENCES public.restaurants_dish(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5916 (class 2606 OID 18696)
-- Name: restaurants_reservationitem restaurants_reservat_reservation_id_4c05e284_fk_restauran; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_reservationitem
    ADD CONSTRAINT restaurants_reservat_reservation_id_4c05e284_fk_restauran FOREIGN KEY (reservation_id) REFERENCES public.restaurants_reservation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5906 (class 2606 OID 18663)
-- Name: restaurants_reservation restaurants_reservation_table_id_2ac0dd3f_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_reservation
    ADD CONSTRAINT restaurants_reservation_table_id_2ac0dd3f_fk FOREIGN KEY (table_id) REFERENCES public.restaurants_table(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5907 (class 2606 OID 17767)
-- Name: restaurants_reservation restaurants_reservation_user_id_1018ff81_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_reservation
    ADD CONSTRAINT restaurants_reservation_user_id_1018ff81_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5919 (class 2606 OID 18825)
-- Name: restaurants_restaurantamenity restaurants_restaura_category_id_b0d5e9b0_fk_restauran; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_restaurantamenity
    ADD CONSTRAINT restaurants_restaura_category_id_b0d5e9b0_fk_restauran FOREIGN KEY (category_id) REFERENCES public.restaurants_amenitycategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5920 (class 2606 OID 18830)
-- Name: restaurants_restaurantamenity restaurants_restaura_restaurant_id_37c5d4e0_fk_restauran; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_restaurantamenity
    ADD CONSTRAINT restaurants_restaura_restaurant_id_37c5d4e0_fk_restauran FOREIGN KEY (restaurant_id) REFERENCES public.restaurants_restaurant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5910 (class 2606 OID 18620)
-- Name: restaurants_restaurantimage restaurants_restaurantimage_restaurant_id_395a3a59_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_restaurantimage
    ADD CONSTRAINT restaurants_restaurantimage_restaurant_id_395a3a59_fk FOREIGN KEY (restaurant_id) REFERENCES public.restaurants_restaurant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5905 (class 2606 OID 18630)
-- Name: restaurants_table restaurants_table_restaurant_id_0a055aef_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_table
    ADD CONSTRAINT restaurants_table_restaurant_id_0a055aef_fk FOREIGN KEY (restaurant_id) REFERENCES public.restaurants_restaurant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5917 (class 2606 OID 18731)
-- Name: restaurants_userprofile restaurants_userprofile_user_id_d4c38052_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_userprofile
    ADD CONSTRAINT restaurants_userprofile_user_id_d4c38052_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-05-11 02:51:08

--
-- PostgreSQL database dump complete
--

\unrestrict BbxC4zOKhdc2r4FnNn5GAUyWvgWgLd44FFmr9PE3Qn8nkzheKHvRplbgATp3wY7

