# Generated by Django 6.0.1 on 2026-02-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='district',
            field=models.CharField(choices=[('Q1', 'Quận 1'), ('Q3', 'Quận 3'), ('Q4', 'Quận 4'), ('Q5', 'Quận 5'), ('Q7', 'Quận 7'), ('BT', 'Bình Thạnh'), ('PN', 'Phú Nhuận'), ('TP', 'Tân Phú')], default='Q1', max_length=10, verbose_name='Quận'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/', verbose_name='Ảnh quán'),
        ),
    ]
