# Generated by Django 6.0.1 on 2026-02-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurant_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Chờ xác nhận'), ('confirmed', '✅ Đã duyệt'), ('cancelled', '❌ Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
