# Generated by Django 6.0.1 on 2026-04-05 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_reservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rating', models.IntegerField(choices=[(1, '⭐ Rất tệ'), (2, '⭐⭐ Tệ'), (3, '⭐⭐⭐ Bình thường'), (4, '⭐⭐⭐⭐ Tốt'), (5, '⭐⭐⭐⭐⭐ Tuyệt vời')], verbose_name='Đánh giá')),
                ('message', models.TextField(verbose_name='Nội dung phản hồi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã xem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_gallery/', verbose_name='Ảnh')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='restaurants.restaurant', verbose_name='Quán ăn')),
            ],
            options={
                'verbose_name': 'Ảnh quán ăn',
                'verbose_name_plural': 'Ảnh quán ăn',
            },
        ),
    ]
