# Generated by Django 5.2.12 on 2026-04-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_dish_id_alter_feedback_id_alter_reservation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_price_representative',
            field=models.BooleanField(default=False, verbose_name='Dùng làm giá đại diện'),
        ),
    ]
