# Generated by Django 5.2.12 on 2026-04-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_reservation_queue_position_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('restaurant', 'customer_email'), name='unique_feedback_email_per_restaurant'),
        ),
    ]
