# Generated by Django 5.2.12 on 2026-04-13 06:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_alter_dish_id_alter_feedback_id_alter_pickuporder_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'Món ăn', 'verbose_name_plural': 'Món ăn'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phản hồi', 'verbose_name_plural': 'Phản hồi'},
        ),
        migrations.AlterModelOptions(
            name='pickuporder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn đặt lấy món', 'verbose_name_plural': 'Đơn đặt lấy món'},
        ),
        migrations.AlterModelOptions(
            name='pickuporderitem',
            options={'verbose_name': 'Chi tiết đơn lấy món', 'verbose_name_plural': 'Chi tiết đơn lấy món'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-booking_time'], 'verbose_name': 'Đặt bàn', 'verbose_name_plural': 'Đặt bàn'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quán ăn', 'verbose_name_plural': 'Quán ăn'},
        ),
        migrations.AlterModelOptions(
            name='restaurantimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Ảnh quán ăn', 'verbose_name_plural': 'Ảnh quán ăn'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['id'], 'verbose_name': 'Bàn', 'verbose_name_plural': 'Bàn'},
        ),
        migrations.RenameField(
            model_name='restaurantimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='dish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickuporderitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_order_items', to='restaurants.dish', verbose_name='Món ăn'),
        ),
        migrations.AlterField(
            model_name='pickuporderitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booking_time',
            field=models.DateTimeField(verbose_name='Thời gian đặt'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_people',
            field=models.PositiveIntegerField(verbose_name='Số người'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('confirmed', 'Đã xác nhận'), ('waiting', 'Hàng chờ'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.table'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên quán'),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='restaurants.restaurant', verbose_name='Quán ăn'),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(default=4, verbose_name='Sức chứa'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Còn sử dụng'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(max_length=10, verbose_name='Số bàn'),
        ),
    ]
