# Generated by Django 6.0.1 on 2026-04-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_add_reservation_item_and_updates'),
    ]

    operations = [
    ]
