# Generated by Django 6.0.1 on 2026-04-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_add_reservation_item_and_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantintroduction',
            options={'ordering': ['-featured', '-created_at'], 'verbose_name': 'Bài giới thiệu quán ăn', 'verbose_name_plural': 'Bài giới thiệu quán ăn'},
        ),
        migrations.RemoveConstraint(
            model_name='reservationitem',
            name='unique_reservation_dish',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='Giờ hoạt động'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='restaurantintroduction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc'),
        ),
        migrations.AlterField(
            model_name='restaurantintroduction',
            name='description',
            field=models.TextField(verbose_name='Nội dung giới thiệu'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationitem',
            unique_together={('reservation', 'dish')},
        ),
    ]
