# Generated by Django 6.0.1 on 2026-04-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_revert_district_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservationitem',
            name='unique_reservation_dish',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(
                blank=True,
                max_length=254,
                verbose_name='Email',
            ),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name='Giờ hoạt động',
            ),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name='Số điện thoại',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='reservationitem',
            unique_together={('reservation', 'dish')},
        ),
    ]