# Generated by Django 6.0.1 on 2026-04-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_alter_restaurantintroduction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='district',
            field=models.CharField(max_length=100, verbose_name='Quận/Huyện'),
        ),
    ]
