# Generated by Django 6.0.1 on 2026-04-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_revert_district_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='district',
            field=models.CharField(choices=[('1', 'Quận 1'), ('3', 'Quận 3'), ('4', 'Quận 4'), ('5', 'Quận 5'), ('6', 'Quận 6'), ('7', 'Quận 7'), ('8', 'Quận 8'), ('10', 'Quận 10'), ('11', 'Quận 11'), ('12', 'Quận 12'), ('TB', 'Tân Bình'), ('TP', 'Tân Phú'), ('BT', 'Bình Thạnh'), ('PN', 'Phú Nhuận'), ('GV', 'Gò Vấp'), ('TD', 'Thủ Đức')], max_length=10, verbose_name='Quận/Huyện'),
        ),
    ]
