# Generated by Django 6.0.1 on 2026-04-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_delete_restaurantintroduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='long_description',
            field=models.TextField(blank=True, help_text='Mô tả chi tiết về quán: lịch sử, phong cách, đặc biệt, giờ hoạt động, v.v.', null=True, verbose_name='Mô tả dài'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả ngắn'),
        ),
    ]
