# Generated by Django 5.2.13 on 2026-05-01 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_alter_restaurantintroduction_options_and_more'),
        ('restaurants', '0022_amenitycategory_restaurantamenity'),
    ]

    operations = [
    ]
