# Generated by Django 5.2.13 on 2026-05-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0024_fix_userprofile_and_reset_token_schema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="email",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="opening_hours",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="phone",
        ),
    ]
